import json
from pymongo import MongoClient

# 1. Connect to local MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['compliance_engine']
controls_collection = db['controls']

# 2. Load the raw audit data generated by Bash
try:
    with open('audit_results.json', 'r') as f:
        audit_data = json.load(f)
except FileNotFoundError:
    print("Error: audit_results.json not found. Run the Bash script first.")
    exit()

print("\n" + "="*50)
print(" LINUX INFRASTRUCTURE COMPLIANCE REPORT ")
print("="*50 + "\n")

# 3. Process each audited item and query MongoDB for context
for item in audit_data:
    control_id = item['control_id']
    status = item['status']
    
    # Fetch the control rules from the database
    control_info = controls_collection.find_one({"control_id": control_id})
    
    if control_info:
        print(f"Control ID : {control_id}")
        print(f"Status     : {status}")
        print(f"Rule Name  : {control_info['name']}")
        print(f"Frameworks : CIS {control_info['framework_mapping']['CIS']} | ISO {control_info['framework_mapping']['ISO_27001']}")
        
        # If the server failed the audit, print the remediation steps
        if status != "PASS":
            print(f"Severity   : {control_info['severity']}")
            print(f"Fix Action : {control_info['technical_details']['remediation']}")
    else:
        print(f"Control ID {control_id} found in audit, but missing from database.")
    
    print("\n" + "-"*50)
